name: Tarea técnica
description: Trabajo técnico sin impacto directo en el usuario (setup, CI, infraestructura...)
labels: ["tarea"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
    validations:
      required: true
  - type: textarea
    id: criterios
    attributes:
      label: Criterios de aceptación
      value: |
        - [ ]
    validations:
      required: true
